### ISSUE TITLE
Arabic language file

### ISSUE THREAD

**Issue by 7oda187** [z0m8i3/abandoned-carts-opencart#2]
Hello dear,

I have translated the Arabic file language for this extension.

Here is attached below.
[ar.zip](https://github.com/z0m8i3/abandoned-carts-opencart/files/1835297/ar.zip)

**Comment by z0m8i3** [comment]
@Muhayshi posted a merge this morning:
https://github.com/z0m8i3/abandoned-carts-opencart/pull/1

I haven't been able to repackage the zip yet, as I was at work.  I will be updating the repo + the Open Cart Marketplace shortly.

If you would like to submit any changes to Ahmed's translation, please open a new pull request?

Thanks for the contribution!
