### ISSUE TITLE
Amount in notification that does not appear on page

### ISSUE THREAD

**Issue by KEVAO28** [z0m8i3/abandoned-carts-opencart#3]
Hello, I was talking to you about a problem that had happened in the opencart forum. I managed to install the module successfully but when I go to the abandoned carts on notification shows the amount 6, but when I open the page to send the message does not appear any. Could you let me know why this occurs?

http://prntscr.com/iumdjd

**Comment by z0m8i3** [comment]
Glad you got it working!

I suspect this is possibly a bug with the dates configuration, I can check a bit closer tomorrow. (11pm here)

For a test, can you extend the days to search back, in the configuration? If you set it to a greater number & the records show, its a minor bug I can fix in an update.

**Comment by KEVAO28** [comment]
I changed to 2 3 5 10 15 and in the 30 gave internal error in server 500 http. Soon I help with the translation of this module in Brazilian Portuguese;)
