### ISSUE TITLE
Module translation contribution to Portuguese Brazil

### ISSUE THREAD

**Issue by KEVAO28** [z0m8i3/abandoned-carts-opencart#4]
I translated the module into my native language that is Brazilian Portuguese, I hope this contribution is a way to help the developer.

[pt-br.zip](https://github.com/z0m8i3/abandoned-carts-opencart/files/1838654/pt-br.zip)

**Comment by z0m8i3** [comment]
Thank you!
I will include this in the next update.

How would you like attribution?  A link to your Github/site/name?
