### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KEVAO28** [z0m8i3/abandoned-carts-opencart#5]
Hello look at me here again hahaha! After updating the extension I get the following error: 
Notice: Undefined index: days in /home/webtrevo/public_html/admin/model/extension/module/abandoned_carts.php on line 106

Print: http://prntscr.com/iv4wyo

Could you help me?

**Comment by z0m8i3** [comment]
Are you updated to the latest version (1.0.2); if so, how did you update?

If you look on [line 106](https://github.com/z0m8i3/abandoned-carts-opencart/blob/master/upload/admin/model/extension/module/abandoned_carts.php) it's looking for 'days' to be passed; which is coming from [index.xml](https://github.com/z0m8i3/abandoned-carts-opencart/blob/master/install.xml) (line 27) - and index.xml instructs OpenCart to rewrite some pieces of the header; so if you missed this file (possibly by installing the update by hand & not through the extensions installer?), you'll have to ensure you have it.

If you installed by hand, the file you'll want to update it.  It can be found in:
/public_html/system/storage/modification/admin/controller/common/header.php

However, this edit might be lost when you refresh the modifications cache, so for good measure, go into phpmyadmin & locate the *modification* table; locate the Abandoned Carts entry -> Edit -> Replace everything in the `xml` row with [index.xml](https://github.com/z0m8i3/abandoned-carts-opencart/blob/master/install.xml) and bump up the version number in the `code` and `version` rows.

Once this is done, refresh the modification cache in the admin panel.

For future upgrades, you don't need to upgrade by hand - use the extension installer. :relaxed:

**Comment by KEVAO28** [comment]
Thank you for helping me solve the problem. I have a question ... Are the requests that appear in the abandoned carts an order that was not generated? Because I have some orders with the status "waiting for payment" and they do not appear there I think it would be a good idea to also filter the orders that contain the initial status of the order that in my case is awaiting payment. This would be an idea for you to further improve the module. Thank you again for your help and attention.

**Comment by z0m8i3** [comment]
Currently it only pulls orders with the status '0' - which is on un-customized carts, the 'default' that an order saves to as a user progresses through the checkout process.  So if they never submit a payment, it says at 0.

I don't pull other statuses with it, because statuses can be deleted, renamed/re-purposed; so they may not be the same for every shop.

Can you elaborate on what you mean by this?
> I have some orders with the status "waiting for payment" and they do not appear there I think it would be a good idea to also filter the orders that contain the initial status of the order that in my case is awaiting payment.

These are not currently accessible to you?

**Comment by KEVAO28** [comment]
I said that it would be a good idea to also filter the orders that have pending payments, since there are many people who place the order and do not make the payment ... It would be another great way to remind them about the order. I have a question for example ... if I add some products in the cart will the module make it appear in the list of abandoned carts from the date "x" that was configured on the administration page?

**Comment by z0m8i3** [comment]
Oh I understand what you're referring to now.  I think such a feature might be useful to others, too.  I'll try to work this in!

> if I add some products in the cart will the module make it appear in the list of abandoned carts from the date "x" that was configured on the administration page?

No, this module doesn't go through the carts at all.  It only checks for users who actually began the checkout process and went away before committing a payment.

**Comment by KEVAO28** [comment]
Great! Another question, I have tried to find where can I translate the subject of the email that the client receives for me he is in English, what location is the subject of the email could inform me?

**Comment by z0m8i3** [comment]
It's hardcoded (something I forgot to fix when I turned this codebase into an extension), I'm putting the finishing touches on the next release and will get this in there so it pulls off the language files, instead.

Thanks so much for reporting these bugs! :smiley:

**Comment by z0m8i3** [comment]
Sorry for the delay, got sidetracked with a few things.

If you will be upgrading via the admin panel, please pay attention to the [upgrade instructions](../blob/master/upgrade-instructions.md)!

Disabling the old versions is essential, otherwise you'll have multiple instances running & it will gunk up your menu.
